### PR TITLE
Add test for world model

### PR DESCRIPTION
**Pull request by thebugcatcher**

### CODE REVIEW

**Comment by thebugcatcher** [comment]
@dat1010 I have added Continuous Integration with Travis CI. It starts a job for automated testing whenever we push to any branch of this repository. I tested a few of the CI's available tonight, but found this one to work the best. Let me know if you have any questions/doubts/suggestions regarding this. 
Testing will be a key part of this project!

Also, "wip- label" stands for Work in Progress.. So, not to be merged into master yet.

**Comment by thebugcatcher** [comment]
Great job.. Literally, nothing would have stopped us from programming today.. :+1: 

alt tag

**Comment by dat1010** [comment]
@aditya7iyengar  haha! we got a great start. I love that tv show. 
I'm learning more about the shell now, and good idea on the wip tag.

**Comment by dat1010** [comment]
tumblr_n1b2c3xl171st1te9o1_500

**Comment by thebugcatcher** [comment]
@dat1010 Should I merge this one in?

**Pull request merged**
