### PR TITLE
Upgrade User; Import ThreeJS; Restructure Directory

### PR DESCRIPTION
**Pull request by dat1010**

### CODE REVIEW

**Comment by dat1010** [comment]
@aditya7iyengar So I figured out that we can have foreign keys related to the User class that comes with django. I just need to figure out how to drop the user table we created. I tried removing the model user and running a migrate, but i got an error saying "user is already registered". so ill have to keep working on it.

**Comment by thebugcatcher** [comment]
try this: python manage.py sqlclear
and then re-run the migration

**Comment by dat1010** [comment]
logicworld

@aditya7iyengar  I need a ER diagram refresher, but I'm still not sure how we want the DB. Is this close to what you were thinking?

**Comment by thebugcatcher** [comment]
I'm not sure. This was supposed to be our backup if we couldn't figure other stuff out. We'll probably have to discuss this later sometime.

**Comment by thebugcatcher** [comment]
I'm gonna be working on this a little bit, just letting you know so we don't have merge conflicts later on. :)

**Comment by thebugcatcher** [comment]
TODO: Migration.

**Pull request merged**
